### ISSUE TITLE
Endpoint is down - 'internal server error'

### ISSUE THREAD

**Issue by dicknorris** [LawnTennisAssociation/opendata#11]
The LTA endpoint appears to be down: https://api.clubspark.uk/odi/public/courses

The following error message is given:

"Message": "InternalServerError",
"ExceptionMessage": "The type 'schema.org.QuantitativeValue' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order.",
"ExceptionType": "SwaggerException",
"RootExceptionMessage": "The type 'schema.org.QuantitativeValue' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order.",
"RootExceptionType": "NotSupportedException"
}

**Comment by peter-dolkens** [comment]
Resolved
