### ISSUE TITLE
Items being removed from the feed instead of being marked as 'deleted'

### ISSUE THREAD

**Issue by civsiv** [LawnTennisAssociation/opendata#13]
Hi,

My name is Civ, and we are using your data feed at imin. We have noticed that items regularly disappear from your feed instead of being marked as 'deleted'. This makes things very difficult for us as we have no way of knowing what sessions are still relevant without resyncing your entire feed. An example of this would be `bc5842e1-820f-419c-bea5-3bb8c8ae572b` which used to be in your feed, and is in the future (at time of writing), but is no longer in your feed.

It would be greatly appreciated if you make this change 🙂 

Thanks,
Civ

**Comment by peter-dolkens** [comment]
Hi @civsiv 

I've looked into this, and the mentioned course was not "deleted", it simply has no further "upcoming" sessions, and thus is no longer included in the feed.

If new sessions are added to the course at a later date, it will be included into the feed again.

We did check this behavior with @nickevansuk, but there may have been a miscommunication / misunderstanding over the intent.
