### ISSUE TITLE
Gender listed as mixed but Tennis Tuesdays is for women only

### ISSUE THREAD

**Issue by tomoakley** [LawnTennisAssociation/opendata#3]
Hi, all the sessions in your endpoint are listed as 'mixed' for `genderRestriction` but on your website, it says Tennis Tuesdays is for women only - [this one for example](https://clubspark.lta.org.uk/TennisTuesdays/Summary/58e31d4d-6ea3-4ca7-94bc-8a62b18a4b1f).

**Comment by tomoakley** [comment]
Also Advantage Tennis Training is listed as male-only on your website, but 'mixed' in the endpoint.

**Comment by peter-dolkens** [comment]
This appears to be resolved
