### ISSUE TITLE
Mismatch between email in endpoint and email on website

### ISSUE THREAD

**Issue by tomoakley** [LawnTennisAssociation/opendata#4]
Hi, the email listed for some sessions in your endpoint is different to the email listed on a session's webpage. I have listed a few examples below:

- [58e31d4d-6ea3-4ca7-94bc-8a62b18a4b1f](https://clubspark.lta.org.uk/TennisTuesdays/Summary/58e31d4d-6ea3-4ca7-94bc-8a62b18a4b1f)
Website shows: matthew@cattaway.com, endpoint shows: <redacted>@willtowin.co.uk
- [5dc3bde7-8d54-4749-84f6-ce9299b57772](https://clubspark.lta.org.uk/AdvantageTennisTraining/Summary/5dc3bde7-8d54-4749-84f6-ce9299b57772) website shows: sportsbooking@rbkc.gov.uk, endpoint shows: info@hollandparktennis.com

**Comment by peter-dolkens** [comment]
Unable to reproduce - I believe this has been fixed.
