### ISSUE TITLE
Data representation as UTC

### ISSUE THREAD

**Issue by domfennell** [LawnTennisAssociation/opendata#6]
Hi,

We're pulling your data into our platform - great to have _Tennis Tuesdays_ and _Advantage Tennis Training_ in there! :) 

Just to check, is your timezone set to BST+1 time? Looking at section 4.5.3.1 of the [OpenActive RPDE](https://www.openactive.io/realtime-paged-data-exchange/), _All dates within <data> must be represented as UTC using [ISO8601] e.g. "2014-08-12T18:50:00Z", including the trailing Z where relevant for clarity of timezone. Dates should be represented without offset from UTC (e.g. "2014-08-12T18:50:00Z" instead of "2016-07-13T20:00:00-05:00")._ If it is BST+1 time, do you think it could be amended to UTC, please?

Thanks and best,

Dom

**Comment by peter-dolkens** [comment]
Hi @domfennell - We're currently meeting the spec as linked, and using the Microsoft standard JSON.Net ISO8601 support to do so, as we have data across multiple timezones in our system.

Is there any reason why your platform is unable to fully comply with ISO8601, including timezone support? We'd rather not write (and support) additional code to support non-standard formats where possible.

I'll talk with the team to confirm how we want to progress things on our end, but I'd imagine the most resilient approach would be for ISO8601 to be supported in its entirety on your end.

**Comment by domfennell** [comment]
Hi, @dolkensp. Not to worry - was just checking. Happy to make the change our end and consume it in its current format, so no need to approach it in another way.

Thanks for getting back to me.

**Comment by peter-dolkens** [comment]
@domfennell 

I've found a smaller change that lets us continue to leverage the Json.Net library for conversions with minimal changes / maintenance.

Will still check with the team how they want to approach this given we're multi-timezone, but should be able to convert it by the next release milestone if there's no other objections.

**Comment by domfennell** [comment]
Thanks, @dolkensp! Appreciate your efforts. Look forward to hearing how you get on.

**Comment by nishaldesai** [comment]
Hey @dolkensp ! Just looking at the fastest way to get the tennis data flowing onto the platform. I've made a task to reflect your suggestions above (that our platform comply with the relevant ISO), but in the meantime was wondering if your team had given the greenlight for the Json.Net library and if it had made it into the next release milestone (or perhaps released already)?

**Comment by peter-dolkens** [comment]
Sorry for the delayed response, but this went live back in August 2017
