### ISSUE TITLE
Fix items.data.subEvent.start and items.data.subEvent.end

### ISSUE THREAD

**Issue by nickevansuk** [LawnTennisAssociation/opendata#7]
Just noticed an inconsistency in these fields... they should be `startDate` and `endDate` rather than `start` and `end`

See https://www.openactive.io/modelling-opportunity-data/#describing-events-code-schema-event-code-

**Comment by peter-dolkens** [comment]
Odd - don't know where I got start/end from - they're explicitly renamed from StartDate/EndDate too :\

Updated for next release.
